module(name = "plaid_lint_example")

bazel_dep(name = "plaid_lint", version = "0.0.0")
local_path_override(
    module_name = "plaid_lint",
    path = "../..",
)

bazel_dep(name = "rules_go", version = "0.62.0")
bazel_dep(name = "gazelle", version = "0.52.2")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.26.5")
