load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "metric",
    srcs = [
        "data.go",
        "exporter.go",
        "info.go",
    ],
    importpath = "github.com/conductorone/plaid-lint/internal/gopls/internal/event/export/metric",
    visibility = ["//internal/gopls:__subpackages__"],
    deps = [
        "//internal/gopls/internal/event",
        "//internal/gopls/internal/event/core",
        "//internal/gopls/internal/event/keys",
        "//internal/gopls/internal/event/label",
    ],
)
