load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "lib",
    srcs = ["lib.go"],
    importpath = "example.com/plaidexample/lib",
    visibility = ["//visibility:public"],
)

go_test(
    name = "lib_test",
    visibility = ["//visibility:public"],
    srcs = ["lib_test.go"],
    embed = [":lib"],
)
