load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "engine",
    srcs = [
        "canonicalize.go",
        "dep_override.go",
        "doc.go",
        "engine.go",
        "l0.go",
        "plan.go",
    ],
    importpath = "github.com/conductorone/plaid-lint/internal/engine",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/analyzers",
        "//internal/cache",
        "//internal/canonicalpath",
        "//internal/config",
        "//internal/exclusion",
        "//internal/gopls/cache",
        "//internal/gopls/cache/metadata",
        "//internal/gopls/file",
        "//internal/gopls/protocol",
        "//internal/gopls/settings",
        "//internal/l0",
        "//internal/output",
        "//internal/registry",
        "//internal/subproc",
        "//internal/workspace",
        "@org_golang_x_sync//errgroup",
        "@org_golang_x_tools//go/analysis",
    ],
)

go_test(
    name = "engine_test",
    srcs = [
        "analyzer_selector_test.go",
        "canonicalize_crossmachine_test.go",
        "canonicalize_l1l2_crossmachine_test.go",
        "canonicalize_test.go",
        "engine_test.go",
        "excluded_roots_test.go",
        "l0_cacheversion_test.go",
        "l0_test.go",
        "streaming_filter_test.go",
        "unused_testfiles_test.go",
    ],
    embed = [":engine"],
    deps = [
        "//internal/analyzers",
        "//internal/cache",
        "//internal/canonicalpath",
        "//internal/config",
        "//internal/exclusion",
        "//internal/gopls/cache",
        "//internal/gopls/cache/metadata",
        "//internal/gopls/protocol",
        "//internal/l0",
        "//internal/output",
        "//internal/registry",
        "//internal/subproc",
        "//internal/test/cachetest",
        "@org_golang_x_tools//go/analysis",
    ],
)
