// Copyright 2026 The plaid-lint Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package engine

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/conductorone/plaid-lint/internal/config"
	"github.com/conductorone/plaid-lint/internal/exclusion"
	"github.com/conductorone/plaid-lint/internal/gopls/cache/metadata"
	"github.com/conductorone/plaid-lint/internal/gopls/protocol"
	"github.com/conductorone/plaid-lint/internal/registry"
)

func TestPruneExcludedRoots(t *testing.T) {
	dir := t.TempDir()
	excluded := filepath.Join(dir, "generated.go")
	included := filepath.Join(dir, "source.go")
	for path, content := range map[string]string{
		excluded: "// Code generated by test. DO NOT EDIT.\npackage fixture\n",
		included: "package fixture\n",
	} {
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatalf("write %s: %v", path, err)
		}
	}
	filter, err := exclusion.NewFilter(&config.Config{}, dir, nil)
	if err != nil {
		t.Fatalf("NewFilter: %v", err)
	}
	pkgs := map[metadata.PackageID]*metadata.Package{
		"excluded": {ID: "excluded", CompiledGoFiles: []protocol.DocumentURI{protocol.URIFromPath(excluded)}},
		"included": {ID: "included", CompiledGoFiles: []protocol.DocumentURI{protocol.URIFromPath(included)}},
		"mixed": {
			ID: "mixed",
			CompiledGoFiles: []protocol.DocumentURI{
				protocol.URIFromPath(excluded),
				protocol.URIFromPath(included),
			},
		},
	}

	roots := pruneExcludedRoots(filter, pkgs)
	if _, ok := roots["excluded"]; ok {
		t.Fatal("wholly excluded package remained an analysis root")
	}
	for _, id := range []metadata.PackageID{"included", "mixed"} {
		if _, ok := roots[id]; !ok {
			t.Fatalf("package %q was pruned", id)
		}
	}
	if len(pkgs) != 3 {
		t.Fatalf("input package map was mutated: len = %d", len(pkgs))
	}
}

func TestExcludedDependencyStillProvidesFacts(t *testing.T) {
	t.Setenv("PLAID_CACHE_BACKEND", "local")
	t.Setenv("PLAID_L1_CACHE_BACKEND", "local")
	t.Setenv("PLAID_L2_CACHE_BACKEND", "local")
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/excluded-facts\n\ngo 1.21\n"), 0o600); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "helper"), 0o755); err != nil {
		t.Fatalf("mkdir helper: %v", err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "consumer"), 0o755); err != nil {
		t.Fatalf("mkdir consumer: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "helper", "helper.go"), []byte(`package helper

import "fmt"

func Printf(format string, args ...any) { fmt.Printf(format, args...) }
`), 0o600); err != nil {
		t.Fatalf("write helper package: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "consumer", "consumer.go"), []byte(`package consumer

import "example.com/excluded-facts/helper"

func Use() { helper.Printf("%d", "not a number") }
`), 0o600); err != nil {
		t.Fatalf("write consumer package: %v", err)
	}

	cfg := config.NewDefault()
	cfg.Linters.Default = config.GroupNone
	cfg.Linters.Enable = []string{"govet"}
	reg, _, err := registry.Build(cfg)
	if err != nil {
		t.Fatalf("registry.Build: %v", err)
	}
	hasPrintfFinding := func(t *testing.T, targetFilter bool) bool {
		t.Helper()
		var targets []string
		if targetFilter {
			targets = []string{"./consumer/..."}
		}
		filter, err := exclusion.NewFilter(&config.Config{}, dir, targets)
		if err != nil {
			t.Fatalf("NewFilter: %v", err)
		}
		in := streamingRunInput(t, dir, filter, nil)
		in.Config = cfg
		in.Registry = reg
		in.TargetPatterns = []string{"./consumer/..."}
		res, err := Run(context.Background(), in)
		if err != nil {
			t.Fatalf("Run: %v", err)
		}
		for _, diag := range res.Diagnostics {
			if diag.Linter == "printf" {
				return true
			}
		}
		return false
	}
	if !hasPrintfFinding(t, false) {
		t.Fatal("baseline run did not report the printf finding")
	}
	if !hasPrintfFinding(t, true) {
		t.Fatal("printf finding missing after dependency root pruning")
	}
}
