load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "lru",
    srcs = ["lru.go"],
    importpath = "github.com/conductorone/plaid-lint/internal/gopls/util/lru",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "lru_test",
    srcs = [
        "lru_fuzz_test.go",
        "lru_nil_test.go",
        "lru_test.go",
    ],
    deps = [
        ":lru",
        "@org_golang_x_sync//errgroup",
    ],
)
