load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "export",
    srcs = [
        "id.go",
        "labels.go",
        "log.go",
        "printer.go",
        "trace.go",
    ],
    importpath = "github.com/conductorone/plaid-lint/internal/gopls/internal/event/export",
    visibility = ["//internal/gopls:__subpackages__"],
    deps = [
        "//internal/gopls/internal/event",
        "//internal/gopls/internal/event/core",
        "//internal/gopls/internal/event/keys",
        "//internal/gopls/internal/event/label",
    ],
)

go_test(
    name = "export_test",
    srcs = ["log_test.go"],
    deps = [
        ":export",
        "//internal/gopls/internal/event",
        "//internal/gopls/internal/event/core",
        "//internal/gopls/internal/event/keys",
        "//internal/gopls/internal/event/label",
    ],
)
