load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "eventtest",
    srcs = ["eventtest.go"],
    importpath = "github.com/conductorone/plaid-lint/internal/gopls/internal/event/export/eventtest",
    visibility = ["//internal/gopls:__subpackages__"],
    deps = [
        "//internal/gopls/internal/event",
        "//internal/gopls/internal/event/core",
        "//internal/gopls/internal/event/export",
        "//internal/gopls/internal/event/label",
    ],
)
