load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "gopathwalk",
    srcs = ["walk.go"],
    importpath = "github.com/conductorone/plaid-lint/internal/gopls/internal/gopathwalk",
    visibility = ["//internal/gopls:__subpackages__"],
)

go_test(
    name = "gopathwalk_test",
    srcs = ["walk_test.go"],
    embed = [":gopathwalk"],
)
